/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        Carro carro = new Carro("Gol City 2014", "Branco", new Motor(1800,72));
        ArrayList<Motor> motores = new ArrayList<Motor>();

        motores.add(carro.getMotor());

        carro.trocarMotor(new Motor(1850, 78));

        carro = new Carro("Uno de Escada", "Branco", motores.get(0));

        System.out.println(carro);
    }
}
