/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Ponto p1 = new Ponto(2,6);
        Ponto p2 = new Ponto(3,9);

        System.out.println("A distância é "+ p1.distancia(p2)+" ou, √"+Math.pow(p1.distancia(p2),2));

        p1.setX(24);
        p1.setY(24);

        p2.setX(25);
        p2.setY(25);

        System.out.println("A distância é "+ p1.distancia(p2)+" ou, √"+Math.pow(p1.distancia(p2),2));
    }
}
