/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Buzz buzz = new Buzz();

        System.out.println(buzz.soltarLaser());

        System.out.println(buzz.falarFrase());
        buzz.estadoAsas(true);
        buzz.estadoCapacete(false);

        System.out.println( buzz.estadoAsas(true));
        System.out.println(buzz.estadoCapacete(false));
    }
}
