/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

//        Scanner linha = new Scanner(System.in);
//        int cont = 0;
//        while(linha.hasNext()){
//            cont++;
//            String aux = linha.nextLine();
//
//            System.out.println(cont + " - " + aux.toUpperCase());
//        }

        if(args.length > 0){
            System.out.println("Olá "+args[0]);
        }

    }
}
