/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner linha = new Scanner(System.in);

        while(linha.hasNext()){
            String aux = linha.nextLine();

            System.out.println(aux.toUpperCase());
        }
    }
}
