/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
//        Buzz buzz = new Buzz();
//
//        System.out.println(buzz.soltarLaser());
//
//        System.out.println(buzz.falarFrase());
//        buzz.estadoAsas(true);
//        buzz.estadoCapacete(false);
//
//        System.out.println( buzz.estadoAsas(true));
//        System.out.println(buzz.estadoCapacete(false));
//
//        System.out.println("Capacete aberto? "+buzz.isCapaceteAberto());
//        System.out.println("Asas abertas? "+buzz.isAsasAbertas());
//
//        Caneta caneta = new Caneta();
//        caneta.trocarCartucho("Azul");
//        System.out.println(caneta.desenhar());
//        System.out.println(caneta.desenhar());
//        System.out.println(caneta.desenhar());
//
//        Pessoa cristiano = new Pessoa();
//        cristiano.setNome("Cristiano Ronaldo");
//        cristiano.setCpf("212.341.342-34");
//        cristiano.setEmail("contato@cr7.com.pt");
        Caneta c = new Caneta();
        System.out.println(Caneta.getTotalCanetas());

    }
}
