/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

public class App {

    private HashMap<String, Aluno> alunos;

    public App() {
        this.alunos = new HashMap<>();
    }


    private int menu() {
        Scanner teclado = new Scanner(System.in);
        int opcao;
        do {
            System.out.println("..:: SIGAA Jr ::..");
            System.out.println("1 - Cadastrar");
            System.out.println("2 - Editar");
            System.out.println("3 - Excluir");
            System.out.println("4 - Listar dados de um aluno");
            System.out.println("5 - Listar todos os alunos");
            System.out.println("6 - Sair");
            System.out.println("Entre com uma opção: ");
            opcao = teclado.nextInt();
            return opcao;
        }
        while (opcao != 6);
    }

    private boolean cadastrar() {
        Scanner teclado = new Scanner(System.in);

        System.out.println("..:: Cadastrar aluno ::..");
        System.out.println("- Nome: ");
        String nome = teclado.nextLine();

        System.out.println("- Matrícula: ");
        String matricula = teclado.nextLine();

        System.out.println("- Curso: ");
        String curso = teclado.nextLine();

        System.out.println("- Telefone: ");
        String telefone = teclado.nextLine();

        System.out.println("- Email: ");
        String email = teclado.nextLine();

        System.out.println("- Data de nascimento (dd/mm/aaaa): ");
        String dataString = teclado.nextLine();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(dataString, formato);

        Aluno a = new Aluno(nome, matricula, curso, telefone, email, dataNascimento);

        if (!this.alunos.containsKey(matricula)) {
            alunos.put(matricula, a);
            return true;
        }
        return false;
    }

    private Aluno excluir() {
        Scanner teclado = new Scanner(System.in);
        System.out.println("..:: Excluir aluno ::..");
        System.out.println("Matrícula do aluno: ");
        String matricula = teclado.nextLine();

        return alunos.remove(matricula);
    }

    private boolean listarDados() {
        Scanner teclado = new Scanner(System.in);
        System.out.println("..:: Listar dados de aluno ::..");
        System.out.println("Matrícula do aluno: ");
        String matricula = teclado.nextLine();

        if(alunos.get(matricula) != null){

        }
        System.out.println("Aluno não encontrado!");
        return false;

    }


    private void listarTodos() {
        System.out.println(this.alunos);
    }
//
//    private boolean editar(){
//        return false;
//    }


    public static void main(String[] args) {

        App app = new App();

        int opcao;

        do {
            opcao = app.menu();

            switch (opcao) {
                case 1 -> app.cadastrar();
                case 2 -> System.out.println(2);
                case 3 -> {
                    if (app.excluir() == null) {
                        System.out.println("Matrícula não encontrada");
                    }
                }
                case 4 -> app.listarDados();
                case 5 -> app.listarTodos();
                default -> System.out.println("Opção inválida!");
            }
        }
        while (opcao != 6);

    }



}
